### ISSUE TITLE
Error on loading apps

### ISSUE THREAD

**Issue by matthgyver** [thedixieflatline/mGameController-32-bit#1]
Hi,

I've this error on Assetto Corsa Python console :

````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".\pygame\__init__.py", line 127, in <module>
    from pygame.base import *
ImportError: DLL load failed: %1 n’est pas une application Win32 valide.
````

I'm on Windows 10 64 bits and think that the problem is that pygame is build for 32 bit version.
Have you a builded version for 64bits please ?

Thank you

**Comment by thedixieflatline** [comment]
Thanks for that.
Yes the error would relate to 64 bit support.
Can you tell me are you running Assetto Corsa  or Assetto Corsa Competizione.
There were problems creating a 64bit version a few years ago but I can try again now that support for 64bit is better in Pygame.
I will let you know when I have something to test.

**Comment by matthgyver** [comment]
I'm running Assetto Corsa.
Thank you at you
